export enum DialogTypeEnum {
  LOGON_OPERATOR = 'P_AN',
  LOGOFF_OPERRATOR = 'P_AB',
  CREATE_BATCH = 'C_GEN',
  MOVE_BATCH = 'C_UMB',
  SPLIT_BATCH = 'CNR.SPLITCREATE',
  GOODS_MOVEMENT = 'C_MBEW',
  UPDATE_BATCH = 'CNR.UPDATE',
  SCRAP_BATCH = '',
  BONUS_BATCH = '',
  COPY_BATCH = 'CNR.COPY',
  MERGE_BATCH = 'CNR.SUMMARIZE',
  LOGON_OPERATION = 'A_AN',
  INTERRUPT_OPERATION = 'A_UN',
  PARTIAL_CONFIRM_OPERATION = 'A_TR',
  LOGOFF_OPERATION = 'A_AB',
  LOGON_INPUT_BATCH = 'CE_AN',
  LOGOFF_INPUT_BATCH = 'CE_AB',

  CHANGE_OPERATION_STATUS = 'ANR.SETSTATUS',

  LOCK_OPERATION = 'ANR.SPERREN',
  UNLOCK_OPERATION = 'ANR.ENTSPERREN',

  GENERATE_BATCH_NAME = 'CNRGEN.CREATENR',
  GENERATE_BATCH_CONNECTION = 'CNRBAUM.INSERT',
  CHANGE_OUTPUT_BATCH = 'CA_WL',
  CHANGE_INPUT_BATCH = 'CE_WL',
  LOGON_TOOL = 'RES_AN',
  LOGOFF_TOOL = 'RES_AB',
  CHANGE_MACHINE_STATUS = 'M_MST',
  STROKE_POST = 'M_AST',
  DELETE_BATCH = 'CNR.DELETE',
  UPDATE_TERMINAL = 'SCMD;53',

  SET_ORDER_STATUS = 'ANR.SETSTATUS',

  RESET_MAINTENNANCE = 'RES_WART',
  CREATE_NETWORK = 'ANETZ.INSERT',

  //#region MPL Master

  MPL_CREATE_BUFFER = 'MATPUF.INSERT',
  MPL_DELETE_BUFFER = 'MATPUF.DELETE',
  MPL_SELECT_BUFFER = 'MATPUF.SELECT',

  MPL_CREATE_MAT_MATTYPE = 'MATMATTYP.INSERT',
  MPL_MODIFY_MAT_MATTYPE = 'MATMATTYP.MODIFY',
  MPL_DELETE_MAT_MATTYPE = 'MATMATTYP.DELETE',

  MPL_SELECT_MATTYPE = 'MATTYP.SELECT',
  MPL_CREATE_MATTYPE = 'MATTYP.INSERT',
  MPL_DELETE_MATTYPE = 'MATTYP.DELETE',

  //#endregion

  //#region HLS

  HLS_ASSIGN_OP = 'ANR.EINPLANEN',
  HLS_UNASSIGN_OP = 'ANR.AUSPLANEN',

  //#endregion

  //#region MDE Master

  MDE_SELECT_MACHINE = 'MNR.SELECT',
  MDE_CREATE_MACHINE = 'MNR.INSERT',
  MDE_DELETE_MACHINE = 'MNR.DELETE',

  MDE_SELECT_STATUS_ASSIGN = 'MST.SELECT',
  MDE_COPY_STATUS_ASSIGN = 'MST.COPY',
  MDE_DELETE_STATUS_ASSIGN = 'MST.DELETE',

  MDE_SELECT_COUNTER_ASSIGN = 'MNRCTR.SELECT',
  MDE_COPY_COUNTER_ASSIGN = 'MNRCTR.COPY',
  MDE_CREATE_COUNTER_ASSIGN = 'MNRCTR.INSERT',
  MDE_DELETE_COUNTER_ASSIGN = 'MNRCTR.DELETE',

  MDE_SELECT_GROUP = 'GRP.SELECT',
  MDE_CREATE_GROUP = 'GRP.INSERT',
  MDE_DELETE_GROUP = 'GRP.DELETE',

  MDE_SELECT_GROUP_ASSIGN = 'GRPRES.SELECT',
  MDE_CREATE_GROUP_ASSIGN = 'GRPRES.INSERT',
  MDE_DELETE_GROUP_ASSIGN = 'GRPRES.DELETE',

  MDE_SELECT_REASON_ASSIGN = 'GR.SELECT',
  MDE_COPY_REASON_ASSIGN = 'GR.COPY',
  MDE_CREATE_REASON_ASSIGN = 'GR.INSERT',
  MDE_DELETE_REASON_ASSIGN = 'GR.DELETE',

  //#endregion

  //#region HLS Master

  HLS_SELECT_PROD_VAR = 'FERTVAR.SELECT',
  HLS_CREATE_PROD_VAR = 'FERTVAR.INSERT',
  HLS_DELETE_PROD_VAR = 'FERTVAR.DELETE',

  //#endregion

  //#region WRM Master

  WRM_SELECT_RESOURCE = 'RES.SELECT',
  WRM_CREATE_RESOURCE = 'RES.INSERT',
  WRM_DELETE_RESOURCE = 'RES.DELETE',

  WRM_SELECT_RES_MAINTENNANCE = 'RESWART.SELECT',
  WRM_CREATE_RES_MAINTENNANCE = 'RESWART.INSERT',
  WRM_DELETE_RES_MAINTENNANCE = 'RESWART.DELETE',

  //#endregion

  //#region HR Master

  HR_CREATE_PERSON = 'HR_CREATE_PERSON',
  HR_DELETE_PERSON = 'HR_DELETE_PERSON',

  //#endregion
  COPY_MACHINE = 'MNR.COPY',

  COPY_MACHINE_STATUS = 'MST.COPY',
  DELETE_MACHINE_STATUS = 'MST.DELETE',

  NEW_MACHINE_STATUS = 'MST.NEW',

  CREATE_MAT_TYPE_ASSIGNMENT = 'MATMATTYP.INSERT',
  COPY_RESOURCE_MAINTENANCE = 'RESWART.COPY',
}

export const DIALOG_USER = 2500;

export const MACHINE_STATUS_CHANGOVER_SETUP = 161;
export const MACHINE_STATUS_CHANGSHIT_SETUP = 160;
export const MACHINE_STATUS_PRODUCTION = 200;
export const MACHINE_STATUS_NOORDER = 399;
