export enum DialogTypeEnum {
  LOGON_OPERATOR = 'P_AN',
  LOGOFF_OPERRATOR = 'P_AB',
  CREATE_BATCH = 'C_GEN',
  MOVE_BATCH = 'C_UMB',
  SPLIT_BATCH = 'CNR.SPLITCREATE',
  GOODS_MOVEMENT = 'C_MBEW',
  UPDATE_BATCH = 'CNR.UPDATE',
  SCRAP_BATCH = '',
  BONUS_BATCH = '',
  COPY_BATCH = 'CNR.COPY',
  MERGE_BATCH = 'CNR.SUMMARIZE',
  LOGON_OPERATION = 'A_AN',
  INTERRUPT_OPERATION = 'A_UN',
  PARTIAL_CONFIRM_OPERATION = 'A_TR',
  LOGOFF_OPERATION = 'A_AB',
  LOGON_INPUT_BATCH = 'CE_AN',
  LOGOFF_INPUT_BATCH = 'CE_AB',
  GENERATE_BATCH_NAME = 'CNRGEN.CREATENR',
  GENERATE_BATCH_CONNECTION = 'CNRBAUM.INSERT',
  CHANGE_OUTPUT_BATCH = 'CA_WL',
  CHANGE_INPUT_BATCH = 'CE_WL',
  LOGON_TOOL = 'RES_AN',
  LOGOFF_TOOL = 'RES_AB',
  CHANGE_MACHINE_STATUS = 'M_MST',
  STROKE_POST = 'M_AST',
  DELETE_BATCH = 'CNR.DELETE',
  UPDATE_TERMINAL = 'SCMD;53',

  SET_ORDER_STATUS = 'ANR.SETSTATUS',

  RESET_MAINTENNANCE = 'RES_WART',
  CREATE_NETWORK = 'ANETZ.INSERT',
  //#region MPL Master

  MPL_CREATE_BUFFER = 'MATPUF.INSERT',
  MPL_DELETE_BUFFER = 'MATPUF.DELETE',

  MPL_ASSIGN_MAT_MATTYPE = 'MATMATTYP.INSERT',
  MPL_MODIFY_MAT_MATTYPE = 'MATMATTYP.MODIFY',

  //#endregion

  //#region HR Master

  HR_CREATE_PERSON = 'HR_CREATE_PERSON',
  HR_DELETE_PERSON = 'HR_DELETE_PERSON',

  //#endregion
}

export const DIALOG_USER = 2500;

export const MACHINE_STATUS_CHANGOVER_SETUP = 161;
export const MACHINE_STATUS_CHANGSHIT_SETUP = 160;
export const MACHINE_STATUS_PRODUCTION = 200;
export const MACHINE_STATUS_NOORDER = 399;
